package chatwoot

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// Client sends visitor messages through Chatwoot's WebWidget API. The
// WebWidget API requires the signed conversation token issued to the browser;
// the administrator API token cannot create incoming messages in a WebWidget
// inbox.
type Client struct {
	base, websiteToken string
	http               *http.Client
}

func New(base, websiteToken string, timeout time.Duration) (*Client, error) {
	if base == "" && websiteToken == "" {
		return nil, nil
	}
	if base == "" || websiteToken == "" {
		return nil, fmt.Errorf("incomplete chatwoot configuration")
	}
	u, err := url.Parse(strings.TrimRight(base, "/"))
	if err != nil || u.Scheme != "https" || u.Host == "" || u.Path != "" || u.RawQuery != "" || u.Fragment != "" {
		return nil, fmt.Errorf("invalid chatwoot base url")
	}
	if err := validateWebsiteToken(websiteToken); err != nil {
		return nil, fmt.Errorf("invalid chatwoot website token: %w", err)
	}
	return &Client{base: u.String(), websiteToken: websiteToken, http: &http.Client{Timeout: timeout}}, nil
}

// SendOrder posts an incoming message to the visitor's existing WebWidget
// conversation. conversationToken is the cw_conversation cookie generated by
// Chatwoot's widget; Chatwoot verifies its signature before accepting it.
func (c *Client) SendOrder(ctx context.Context, conversationToken, content, referer string) error {
	if c == nil {
		return fmt.Errorf("chatwoot client is nil")
	}
	if err := validateToken(conversationToken, 4096); err != nil {
		return fmt.Errorf("invalid chatwoot conversation token: %w", err)
	}
	content = strings.TrimSpace(content)
	if content == "" {
		return fmt.Errorf("chatwoot message content is empty")
	}
	if len(content) > 16*1024 {
		return fmt.Errorf("chatwoot message content is too long")
	}
	if len(referer) > 2048 {
		runes := []rune(referer)
		if len(runes) > 2048 {
			referer = string(runes[:2048])
		}
	}

	endpoint, err := url.Parse(c.base + "/api/v1/widget/messages")
	if err != nil {
		return fmt.Errorf("build chatwoot message url: %w", err)
	}
	query := endpoint.Query()
	query.Set("website_token", c.websiteToken)
	query.Set("locale", "zh_CN")
	endpoint.RawQuery = query.Encode()

	message := map[string]any{
		"content":     content,
		"timestamp":   time.Now().UTC().Format(time.RFC3339Nano),
		"referer_url": referer,
	}
	body, err := json.Marshal(map[string]any{"message": message})
	if err != nil {
		return fmt.Errorf("encode chatwoot message: %w", err)
	}
	request, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint.String(), bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("build chatwoot message request: %w", err)
	}
	request.Header.Set("X-Auth-Token", conversationToken)
	request.Header.Set("Content-Type", "application/json")

	response, err := c.http.Do(request)
	if err != nil {
		return fmt.Errorf("send chatwoot message: %w", err)
	}
	defer response.Body.Close()
	_, _ = io.Copy(io.Discard, io.LimitReader(response.Body, 1<<20))
	if response.StatusCode < 200 || response.StatusCode > 299 {
		return fmt.Errorf("chatwoot status %d", response.StatusCode)
	}
	return nil
}

func validateToken(value string, max int) error {
	if value == "" {
		return fmt.Errorf("is empty")
	}
	if len(value) > max {
		return fmt.Errorf("is too long")
	}
	if strings.IndexAny(value, "\r\n") >= 0 {
		return fmt.Errorf("contains a line break")
	}
	return nil
}

func validateWebsiteToken(value string) error {
	if len(value) < 10 {
		return fmt.Errorf("is too short")
	}
	if err := validateToken(value, 256); err != nil {
		return err
	}
	for _, r := range value {
		if (r < 'A' || r > 'Z') && (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '_' && r != '-' {
			return fmt.Errorf("contains an unsafe character")
		}
	}
	return nil
}
